private ["_tech_matrix"];

_tech_matrix = 
[
	//CTI_UPGRADE_BARRACKS
	[
		//CTI_BW_ID
		[
			//CTI_GM_ID
			[true,true,true,true,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,true,true,true,false],
			//CTI_BWADD_ID
			[false,false,false,true,true,true,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_NVA_ID
		[
			//CTI_GM_ID
			[true,true,true,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_US_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,true,true,true,true],
			//CTI_RHS_ID
			[false,false,false,true,true,true,false],
			//CTI_CWR3_ID
			[true,true,true,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_SOV_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,true,true,true,false],
			//CTI_RHS_ID
			[false,false,false,true,true,true,false],
			//CTI_CWR3_ID
			[true,true,true,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_NPOC_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_RACS_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_FIA_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[true,true,true,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_CDF_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[true,true,true,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_CHDKZ_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[true,true,true,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_UKRAIN_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,true,true,true,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		]
		//CTI_DEN_ID
		//CTI_POL_ID
		//CTI_CZ_ID
		//CTI_SLA_ID
		//CTI_TKA_ID
		//CTI_SAF_ID
		//CTI_SAF_I_ID
		//CTI_HIDF_ID
		//CTI_NAPA_ID
		//CTI_ION_ID
		//CTI_PLA_ID
		//CTI_TK_ID
	],
	//CTI_UPGRADE_LIGHT
	[
		//CTI_BW_ID
		[
			//CTI_GM_ID
			[true,true,true,true,true,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,true,true,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,true,false,false,false,true,true,false,false,false],
			//CTI_REDD_ID
			[false,true,true,true,true,false,false,false,false,false]
		],
		//CTI_NVA_ID
		[
			//CTI_GM_ID
			[true,true,true,true,false,false,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		],
		//CTI_US_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,true,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,true,true,true,true,true,true,false,false],
			//CTI_RHS_ID
			[false,true,true,true,true,true,true,false,false,false],
			//CTI_CWR3_ID
			[true,true,false,true,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		],
		//CTI_SOV_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,true,true,true,true,true,true,true,true,true],
			//CTI_RHS_ID
			[true,true,true,false,false,true,true,true,true,true],
			//CTI_CWR3_ID
			[false,true,true,true,true,true,false,true,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		],
		//CTI_NPOC_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,true,true,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		],
		//CTI_RACS_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,true,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		],
		//CTI_FIA_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[true,true,true,true,true,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		],
		//CTI_CDF_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,true,true,true,true,true,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		],
		//CTI_CHDKZ_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[true,true,false,true,true,true,true,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		],
		//CTI_UKRAIN_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,true,true,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false,false]
		]
		//CTI_DEN_ID
		//CTI_POL_ID
		//CTI_TK_ID
		//CTI_CZ_ID
		//CTI_SLA_ID
		//CTI_TKA_ID
		//CTI_SAF_ID
		//CTI_SAF_I_ID
		//CTI_HIDF_ID
		//CTI_NAPA_ID
		//CTI_ION_ID
		//CTI_PLA_ID
	],
	//CTI_UPGRADE_HEAVY
	[
		//CTI_BW_ID
		[
			//CTI_GM_ID
			[true,true,true,true,true,true,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,true,true,true,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,true,true,true,true,false,false,false]
		],
		//CTI_NVA_ID
		[
			//CTI_GM_ID
			[true,true,true,true,false,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,true,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_US_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,true,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,true,true,true,true,true,true],
			//CTI_RHS_ID
			[true,true,true,true,false,true,true,true,true],
			//CTI_CWR3_ID
			[true,true,true,true,true,true,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_SOV_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,false,true,true,true,true,true,false,false],
			//CTI_RHS_ID
			[true,true,true,true,true,true,true,true,false],
			//CTI_CWR3_ID
			[true,true,true,true,true,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_NPOC_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,true,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_RACS_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,true,true,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_FIA_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[true,true,true,true,true,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_CDF_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[true,true,true,true,true,true,true,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_CHDKZ_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[true,true,true,true,true,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_UKRAIN_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,false,false,false,true,true,true,true,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		]
		//CTI_DEN_ID
		//CTI_POL_ID
		//CTI_TK_ID
		//CTI_CZ_ID
		//CTI_SLA_ID
		//CTI_TKA_ID
		//CTI_SAF_ID
		//CTI_SAF_I_ID
		//CTI_HIDF_ID
		//CTI_NAPA_ID
		//CTI_ION_ID
		//CTI_PLA_ID
	],
	//CTI_UPGRADE_AIR
	[
		//CTI_BW_ID
		[
			//CTI_GM_ID
			[true,true,true,true,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,true,true,true,false,true,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,true,true,true,true,true,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,true,true,false,false,false],
			//CTI_BWADD_ID
			[true,false,true,false,true,true,false,false,false],			//[true,false,true,true,true,true,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_NVA_ID
		[
			//CTI_GM_ID
			[true,true,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,true,true,true,false,true,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,true,true,true,true,true,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_US_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,true,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,true,true,true,true,false,false],
			//CTI_RHS_ID
			[true,true,true,true,true,true,true,false,false],
			//CTI_CWR3_ID
			[true,true,true,true,false,true,true,false,false],
			//CTI_SABAIR_ID
			[false,true,true,true,false,true,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,true,true,true,true,true,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_SOV_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,true,true,true,true,true,true,false,false],
			//CTI_RHS_ID
			[false,true,true,true,true,true,true,false,false],
			//CTI_CWR3_ID
			[false,true,true,true,true,false,false,false,false],
			//CTI_SABAIR_ID
			[false,true,true,true,false,true,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,true,true,true,true,true,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_NPOC_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_RACS_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,true,true,true,true,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_FIA_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[true,true,true,true,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_CDF_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[true,true,true,true,true,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_CHDKZ_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,true,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		],
		//CTI_UKRAIN_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false,false,false]
		]
		//CTI_DEN_ID
		//CTI_POL_ID
		//CTI_TK_ID
		//CTI_CZ_ID
		//CTI_SLA_ID
		//CTI_TKA_ID
		//CTI_SAF_ID
		//CTI_SAF_I_ID
		//CTI_HIDF_ID
		//CTI_NAPA_ID
		//CTI_ION_ID
		//CTI_PLA_ID
	],
	//CTI_UPGRADE_NAVAL
	[
		//CTI_BW_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_NVA_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[true,true,true,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_US_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[true,true,true,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[true,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_SOV_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[true,true,false,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[true,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_NPOC_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_RACS_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,true],
			//CTI_RHS_ID
			[true,true,true,true],
			//CTI_CWR3_ID
			[false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_FIA_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[true,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_CDF_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_CHDKZ_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		],
		//CTI_UKRAIN_ID
		[
			//CTI_GM_ID
			[false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false]
		]
		//CTI_DEN_ID
		//CTI_POL_ID
		//CTI_TK_ID
		//CTI_CZ_ID
		//CTI_SLA_ID
		//CTI_TKA_ID
		//CTI_SAF_ID
		//CTI_SAF_I_ID
		//CTI_HIDF_ID
		//CTI_NAPA_ID
		//CTI_ION_ID
		//CTI_PLA_ID
	],
	[],[],[],[],[],[],[],
	//CTI_UPGRADE_GEAR
	[
		
		//CTI_BW_ID
		[
			//CTI_GM_ID
			[true,true,true,true,true,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,true,true,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,true,true,false,false],
			//CTI_BWADD_ID
			[false,false,false,true,true,false,false],
			//CTI_REDD_ID
			[false,false,false,true,true,false,false]
		],
		//CTI_NVA_ID
		[
			//CTI_GM_ID
			[true,true,true,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_US_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[true,true,true,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,true,true,true,true],
			//CTI_RHS_ID
			[false,false,false,true,true,true,true],
			//CTI_CWR3_ID
			[true,true,true,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_SOV_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,true,true,true,false],
			//CTI_RHS_ID
			[false,false,false,true,true,true,false],
			//CTI_CWR3_ID
			[true,true,true,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_NPOC_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_RACS_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_FIA_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[true,true,true,false,false,false,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_CDF_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[true,true,true,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_CHDKZ_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,false,false,false,false],
			//CTI_RHS_ID
			[true,true,true,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		],
		//CTI_UKRAIN_ID
		[
			//CTI_GM_ID
			[false,false,false,false,false,false,false],
			//CTI_PF_ID
			[false,false,false,false,false,false,false],
			//CTI_IC_ID
			[false,false,false,false,false,false,false],
			//CTI_WS_ID
			[false,false,false,false,false,false,false],
			//CTI_CUP_ID
			[false,false,false,true,true,true,false],
			//CTI_RHS_ID
			[false,false,false,false,false,false,false],
			//CTI_CWR3_ID
			[false,false,false,false,false,false,false],
			//CTI_SABAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_POOKAIR_ID
			[false,false,false,false,false,false,false],
			//CTI_BWA3_ID
			[false,false,false,false,false,false,false],
			//CTI_BWADD_ID
			[false,false,false,false,false,false,false],
			//CTI_REDD_ID
			[false,false,false,false,false,false,false]
		]
		//CTI_DEN_ID
		//CTI_POL_ID
		//CTI_TK_ID
		//CTI_CZ_ID
		//CTI_SLA_ID
		//CTI_TKA_ID
		//CTI_SAF_ID
		//CTI_SAF_I_ID
		//CTI_HIDF_ID
		//CTI_NAPA_ID
		//CTI_ION_ID
		//CTI_PLA_ID
	]
];

missionNamespace setVariable ["CTI_TECHMATRIX", _tech_matrix];
if (CTI_Log_Level >= CTI_Log_Information) then { ["INFORMATION", "FILE: Common\Config\Units\Techmatrx.sqf", format ["Techmatrix are defined <%1|%2|%3>", count (_tech_matrix select 0), count (_tech_matrix select 0 select 0), count (_tech_matrix select 0 select 0 select 0)]] call CTI_CO_FNC_Log };